//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public long Id { get; set; }
        public string NameRu { get; set; }
        public string NameEn { get; set; }
        public string NameFr { get; set; }
        public string FileName { get; set; }
        public string DungeonName { get; set; }
        public string Class { get; set; }
        public string Type { get; set; }
        public string Level { get; set; }
        public string Discriminator { get; set; }
        public string Stage { get; set; }
    }
}
